version: '3.3'

services:
  backend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: prod.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/backend
      - site-packages:/usr/local/lib/python3.8/site-packages
      - bin:/usr/local/bin
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: library/postgres:11.0-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"

volumes:
  site-packages:
  bin:
  postgres-data:
