version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: dev.Dockerfile
      args:
        - DJANGO_ENV=dev
    volumes:
      - ./:/backend
      - site-packages:/usr/local/lib/python3.8/site-packages
      - bin:/usr/local/bin
    ports:
      - 8000:8000
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres

  postgres:
    image: library/postgres:11.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

volumes:
  site-packages:
  bin:
  postgres-data: