# Generated by Django 3.1.4 on 2021-06-16 21:10

from django.db import migrations
from accounts.models import User


def create_admin(apps, schema_editor):
    user = User(username='admin', email='admin@admin.com')
    user.is_superuser = True
    user.is_active = True
    user.is_staff = True
    user.set_password('admin123')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin)
    ]
