# Generated by Django 3.1.4 on 2021-06-16 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
    ]
